var annotated_dup =
[
    [ "Administrator", "classAdministrator.html", "classAdministrator" ],
    [ "administrator_hash", "structadministrator__hash.html", "structadministrator__hash" ],
    [ "AdministratorManager", "classAdministratorManager.html", "classAdministratorManager" ],
    [ "auth_users_hash", "structauth__users__hash.html", "structauth__users__hash" ],
    [ "AuthUser", "classAuthUser.html", "classAuthUser" ],
    [ "AuthUserManager", "classAuthUserManager.html", "classAuthUserManager" ],
    [ "Bootstrap", "classBootstrap.html", "classBootstrap" ],
    [ "Cluster", "classCluster.html", "classCluster" ],
    [ "companies_client_hash", "structcompanies__client__hash.html", "structcompanies__client__hash" ],
    [ "Company", "classCompany.html", "classCompany" ],
    [ "CompanyClient", "classCompanyClient.html", "classCompanyClient" ],
    [ "CompanyClientManager", "classCompanyClientManager.html", "classCompanyClientManager" ],
    [ "CompanyRepresentative", "classCompanyRepresentative.html", "classCompanyRepresentative" ],
    [ "CurrentSession", "classCurrentSession.html", "classCurrentSession" ],
    [ "Edge", "classEdge.html", "classEdge" ],
    [ "Graph", "classGraph.html", "classGraph" ],
    [ "InvalidDirectoryException", "classInvalidDirectoryException.html", "classInvalidDirectoryException" ],
    [ "InvalidFileException", "classInvalidFileException.html", "classInvalidFileException" ],
    [ "InvalidLocationException", "classInvalidLocationException.html", "classInvalidLocationException" ],
    [ "InvalidLoginException", "classInvalidLoginException.html", "classInvalidLoginException" ],
    [ "Location", "classLocation.html", "classLocation" ],
    [ "pointer_wrapper_hash", "structpointer__wrapper__hash.html", "structpointer__wrapper__hash" ],
    [ "PointerWrapper", "classPointerWrapper.html", "classPointerWrapper" ],
    [ "Vertex", "classVertex.html", "classVertex" ]
];