var annotated_dup =
[
    [ "ui_util", "namespaceui__util.html", "namespaceui__util" ],
    [ "Administrator", "classAdministrator.html", "classAdministrator" ],
    [ "administrator_hash", "structadministrator__hash.html", "structadministrator__hash" ],
    [ "AdministratorManager", "classAdministratorManager.html", "classAdministratorManager" ],
    [ "AdministratorUI", "classAdministratorUI.html", "classAdministratorUI" ],
    [ "auth_users_hash", "structauth__users__hash.html", "structauth__users__hash" ],
    [ "AuthUser", "classAuthUser.html", "classAuthUser" ],
    [ "AuthUserManager", "classAuthUserManager.html", "classAuthUserManager" ],
    [ "Bootstrap", "classBootstrap.html", "classBootstrap" ],
    [ "Cluster", "classCluster.html", "classCluster" ],
    [ "companies_client_hash", "structcompanies__client__hash.html", "structcompanies__client__hash" ],
    [ "Company", "classCompany.html", "classCompany" ],
    [ "CompanyClient", "classCompanyClient.html", "classCompanyClient" ],
    [ "CompanyClientManager", "classCompanyClientManager.html", "classCompanyClientManager" ],
    [ "CompanyRepresentative", "classCompanyRepresentative.html", "classCompanyRepresentative" ],
    [ "CurrentSession", "classCurrentSession.html", "classCurrentSession" ],
    [ "Edge", "classEdge.html", "classEdge" ],
    [ "Graph", "classGraph.html", "classGraph" ],
    [ "HomeUI", "classHomeUI.html", "classHomeUI" ],
    [ "InvalidDirectoryException", "classInvalidDirectoryException.html", "classInvalidDirectoryException" ],
    [ "InvalidFileException", "classInvalidFileException.html", "classInvalidFileException" ],
    [ "InvalidLocationException", "classInvalidLocationException.html", "classInvalidLocationException" ],
    [ "InvalidLoginException", "classInvalidLoginException.html", "classInvalidLoginException" ],
    [ "InvalidVertexException", "classInvalidVertexException.html", "classInvalidVertexException" ],
    [ "Location", "classLocation.html", "classLocation" ],
    [ "LoginUI", "classLoginUI.html", "classLoginUI" ],
    [ "ModifyVehiclesUI", "classModifyVehiclesUI.html", "classModifyVehiclesUI" ],
    [ "MutablePriorityQueue", "classMutablePriorityQueue.html", "classMutablePriorityQueue" ],
    [ "Trio", "classTrio.html", "classTrio" ],
    [ "UI", "classUI.html", "classUI" ],
    [ "UIManager", "classUIManager.html", "classUIManager" ],
    [ "Vertex", "classVertex.html", "classVertex" ],
    [ "vertex_hash", "structvertex__hash.html", "structvertex__hash" ]
];